# Generated by Django 3.1 on 2020-08-09 04:47

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page_maker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='votes',
        ),
        migrations.AddField(
            model_name='template',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/placeholder_img.png', editable=False, upload_to='thumbnails/', validators=[django.core.validators.validate_image_file_extension], verbose_name='thumbnail (leave empty-generated automatically)'),
        ),
        migrations.AddField(
            model_name='webpage',
            name='last_edit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webpage',
            name='thumbnail_edit_date',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), editable=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='style_sheet',
            field=models.FileField(upload_to='styles/'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/placeholder_img.png', editable=False, upload_to='thumbnails/', validators=[django.core.validators.validate_image_file_extension], verbose_name='thumbnail (leave empty-generated automatically)'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='user_text_1',
            field=models.TextField(blank=True, verbose_name='subtitle paragraph'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='user_text_3',
            field=models.TextField(blank=True, verbose_name='closing paragraph'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_datetime', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_maker.webpage')),
            ],
        ),
    ]
